Created Netris.md
remoteintech/remote-jobs pull request #1192
Opened 2021-06-16 12:36 UTC by ixodie

Created netris company blurb.

2021-06-16 12:37 UTC, auto-nylen commented
:robot: :warning:

_Sorry, this bot is currently having issues. It's probably @nylen's fault, not yours. We'll look into it._

:robot: :warning:

2021-06-16 22:03 UTC, dougaitken commented
Hi @ixodie can you delete #1135 and add the profile to the main readme file as part of this PR, please?

2021-06-17 11:38 UTC, auto-nylen commented
:robot: :warning:

_Sorry, this bot is currently having issues. It's probably @nylen's fault, not yours. We'll look into it._

:robot: :warning:

2021-06-17 11:52 UTC, ixodie commented
Sorry for the mixup, both file changes have been merged into one PR.

2021-06-19 16:28 UTC, dougaitken requested changes

2021-06-19 16:28 UTC, dougaitken commented on company-profiles/netris.md
> +Posibility to remote work - Get things done - from home or an office.
Spelling error - `possibility`

2021-06-20 19:52 UTC, ixodie reviewed
Updated.

2021-06-20 19:53 UTC, auto-nylen commented
:robot: :warning:

_Sorry, this bot is currently having issues. It's probably @nylen's fault, not yours. We'll look into it._

:robot: :warning:

2021-07-08 14:00 UTC, dougaitken approved these changes

2021-07-08 14:01 UTC, merged