closed #1219 fixed typo on README.md from `pull  reqest` to `pull request`
remoteintech/remote-jobs pull request #1220
Opened 2021-09-30 16:35 UTC by sharechiwai

This pull request is used to fix the type on README.md, e.g. not add/updating company

📝Title your pull request descriptively. `[edit X company]` or `[add new company - COMPANY]`

ℹ️Please read and check the boxes in the list below that apply!

If updating or adding a company, please include details here: _delete this and add details_

- [ ] This PR contains housekeeping only (URL edits, copy changes etc) - if check, delete other lines that don't apply.
- [ ] I am an employee of the company mentioned and confirm all included details are correct.
- [ ] You know your alphabet - company is listed in alphabetical order in the README.md file.
- [ ] The company directly hires employees. No bootcamps / freelance sites / etc
- [ ] The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such.
- [ ] A [company profile](https://github.com/remoteintech/remote-jobs/blob/main/company-profiles/example.md) is included - This is __required__ for new additions.
- [ ] __Remote status__ has details regarding how the culture includes remote employees, how the company integrated remote workers, etc
- [ ] __Region__ details the geographic regions in which this company's employees can reside. For more details see the instructions in the [example company profile](/company-profiles/example.md#region).
- [ ] __How to apply__ details the best approach for new applications, page on site where open position are listed, and any other help available for job hunters

This is a modified version of the [Contributing Guidelines](https://github.com/remoteintech/remote-jobs/blob/main/CONTRIBUTING.md).

This Pull Request should adhere to the repository's [Code of Conduct](https://github.com/remoteintech/remote-jobs/blob/main/CODE_OF_CONDUCT.md).

2021-10-03 13:56 UTC, ANUSHRAVGARG requested changes
my github profile is ANUSHRAV(https://github.com/remoteintech/remote-jobs/blob/main/CONTRIBUTING.md).
I can't able to find the repositroy can u help me out

2021-10-03 14:08 UTC, sharechiwai commented
@ANUSHRAVGARG sorry, I am not sure what you mean...
do you mean `remoteintech/remote-jobs` ?
https://github.com/remoteintech/remote-jobs

or the one I fork? which should be public
https://github.com/sharechiwai/remote-jobs/tree/issue-1219-readme-typo

2021-10-03 14:22 UTC, dougaitken commented
@ANUSHRAVGARG please comment on Issue #1233 with details about how you'd like to contribute.

2021-10-05 09:04 UTC, dougaitken approved these changes

2021-10-05 09:05 UTC, merged