add new company - Bit Zesty
remoteintech/remote-jobs pull request #1376
Opened 2022-06-15 16:17 UTC by matthewford

📝Title your pull request descriptively. `[edit X company]` or `[add new company - COMPANY]`

ℹ️Please read and check the boxes in the list below that apply!

If updating or adding a company, please include details here: 

- [x] I am an employee of the company mentioned and confirm all included details are correct.
- [x] You know your alphabet - company is listed in alphabetical order in the README.md file.
- [x] The company directly hires employees. No bootcamps / freelance sites / etc
- [x] The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such.
- [x] A [company profile](https://github.com/remoteintech/remote-jobs/blob/main/company-profiles/example.md) is included - This is __required__ for new additions.
- [x] __Remote status__ has details regarding how the culture includes remote employees, how the company integrated remote workers, etc
- [x] __Region__ details the geographic regions in which this company's employees can reside. For more details see the instructions in the [example company profile](/company-profiles/example.md#region).
- [x] __How to apply__ details the best approach for new applications, page on site where open position are listed, and any other help available for job hunters

This is a modified version of the [Contributing Guidelines](https://github.com/remoteintech/remote-jobs/blob/main/CONTRIBUTING.md).

This Pull Request should adhere to the repository's [Code of Conduct](https://github.com/remoteintech/remote-jobs/blob/main/CODE_OF_CONDUCT.md).

2022-06-16 17:44 UTC, dougaitken requested changes

2022-06-16 17:44 UTC, dougaitken commented on README.md
> +[Bit Zesty](/company-profiles/bit-zesty.md) | https://bitzesty.com/ | UK & Worldwide
Change to Worldwide to match profile.

2022-06-17 14:53 UTC, matthewford commented on README.md
> +[Bit Zesty](/company-profiles/bit-zesty.md) | https://bitzesty.com/ | UK & Worldwide
@dougaitken sure thing

2022-06-22 23:09 UTC, dougaitken commented
@matthewford Why have you removed CareCru? I think it might be due to the force push. Can you check?

2022-06-23 17:32 UTC, dougaitken approved these changes

2022-06-23 17:32 UTC, merged

2022-06-23 17:32 UTC, dougaitken commented
Thanks @matthewford! Merged.