Added Nagarro into this
remoteintech/remote-jobs pull request #1440
Opened 2022-10-02 14:09 UTC by shivam-jha2712

📝Title your pull request descriptively. `[edit X company]` or `[add new company - COMPANY]`

ℹ️Please read and check the boxes in the list below that apply!

If updating or adding a company, please include details here: _delete this and add details_

- [x] This PR contains housekeeping only (URL edits, copy changes etc) - if check, delete other lines that don't apply.
- [ ] I am an employee of the company mentioned and confirm all included details are correct.
- [x] You know your alphabet - company is listed in alphabetical order in the README.md file.
- [ ] The company directly hires employees. No bootcamps / freelance sites / etc
- [x] The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such.
- [x] A [company profile](https://github.com/remoteintech/remote-jobs/blob/main/company-profiles/example.md) is included - This is __required__ for new additions.
- [x] __Remote status__ has details regarding how the culture includes remote employees, how the company integrated remote workers, etc
- [x] __Region__ details the geographic regions in which this company's employees can reside. For more details see the instructions in the [example company profile](/company-profiles/example.md#region).
- [x] __How to apply__ details the best approach for new applications, page on site where open position are listed, and any other help available for job hunters

This is a modified version of the [Contributing Guidelines](https://github.com/remoteintech/remote-jobs/blob/main/CONTRIBUTING.md).

This Pull Request should adhere to the repository's [Code of Conduct](https://github.com/remoteintech/remote-jobs/blob/main/CODE_OF_CONDUCT.md).

2022-10-02 23:32 UTC, dougaitken commented
@shivam-jha2712 Can you review the company profile, please? There are some odd line breaks and grammar to check. Thanks.

2022-10-03 02:09 UTC, shivam-jha2712 commented
Sure will do the same

On Mon, Oct 3, 2022, 05:03 Doug Aitken ***@***.***> wrote:

> @shivam-jha2712 <https://github.com/shivam-jha2712> Can you review the
> company profile, please? There are some odd line breaks and grammar to
> check. Thanks.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/remoteintech/remote-jobs/pull/1440#issuecomment-1264763552>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARDVKKULGKZPDG5LFYGQBWTWBILSZANCNFSM6AAAAAAQ25NMMY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-10-03 16:04 UTC, shivam-jha2712 commented
> @shivam-jha2712 Can you review the company profile, please? There are some odd line breaks and grammar to check. Thanks.

If you could review it and merge it please

2022-10-03 22:33 UTC, dougaitken requested changes

2022-10-03 22:33 UTC, dougaitken commented on company-profiles/nagarro.md
> +thinking breakthroughs. see how we have helped industry leaders embrace digitalization and accelerate technology-led innovation. We care. Caring is our superpower.
There is an odd line break between `We call it` and `thinking`

2022-10-03 22:33 UTC, dougaitken commented on company-profiles/nagarro.md
> +itdrives us to deliver excellence to our clients.
`It drives` ?

2022-10-03 22:33 UTC, dougaitken commented on company-profiles/nagarro.md
> +Brazil.
Readme says Worldwide. This section is for where in the world the company hires, is it only Brazil, or Worldwide?

2022-10-03 22:33 UTC, dougaitken commented on company-profiles/nagarro.md
> +Austria, Mexico, Sri Lanka, Germany, Poland, India, USA, Romania
Another odd line break.

2022-10-03 22:33 UTC, dougaitken commented on company-profiles/nagarro.md
> +We are higin, visit [Nagarro](https://www.nagarro.com/en/careers) or [Linkedin](https://www.linkedin.com/company/nagarro/)
`hiring` ?

2022-10-04 20:25 UTC, shivam-jha2712 commented
Hey! Have you reviewed it ?

2022-10-04 20:26 UTC, shivam-jha2712 commented
I have completed the said changes could you please review this and merge it

2022-10-05 11:46 UTC, shivam-jha2712 commented
Hey Could you please review this and help me with my last PR

2022-10-05 11:51 UTC, dougaitken commented
If this is for Hacktoberfest @shivam-jha2712 then please be patient, there is no rush.

2022-10-06 23:30 UTC, dougaitken requested changes

2022-10-06 23:30 UTC, dougaitken commented on company-profiles/nagarro.md
> +thinking breakthroughs. see how we have helped industry leaders embrace digitalization and accelerate technology-led innovation. We care. Caring is our superpower.
Unneeded line break.

2022-10-06 23:30 UTC, dougaitken commented on company-profiles/nagarro.md
> +Austria, Mexico, Sri Lanka, Germany, Poland, India, USA, Romania
Unneeded line break

2022-10-07 06:19 UTC, shivam-jha2712 reviewed
Have made the changes removed all the spaces

2022-10-07 22:40 UTC, dougaitken approved these changes

2022-10-07 22:47 UTC, merged