add new company sticker-mule
remoteintech/remote-jobs pull request #1460
Opened 2022-10-05 07:06 UTC by abhirimal

📝Title your pull request descriptively. `[edit X company]` or `[add new company - COMPANY]`

ℹ️Please read and check the boxes in the list below that apply!

If updating or adding a company, please include details here: _delete this and add details_

- [ ] This PR contains housekeeping only (URL edits, copy changes etc) - if check, delete other lines that don't apply.
- [ ] You know your alphabet - company is listed in alphabetical order in the README.md file.
- [ ] The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such.
- [ ] A [company profile](https://github.com/remoteintech/remote-jobs/blob/main/company-profiles/example.md) is included - This is __required__ for new additions.
- [ ] __Remote status__ has details regarding how the culture includes remote employees, how the company integrated remote workers, etc
- [ ] __Region__ details the geographic regions in which this company's employees can reside. For more details see the instructions in the [example company profile](/company-profiles/example.md#region).
- [ ] __How to apply__ details the best approach for new applications, page on site where open position are listed, and any other help available for job hunters

This is a modified version of the [Contributing Guidelines](https://github.com/remoteintech/remote-jobs/tree/main/.github/CONTRIBUTING.md).

This Pull Request should adhere to the repository's [Code of Conduct](https://github.com/remoteintech/remote-jobs/tree/main/.github/CODE_OF_CONDUCT.md).

2022-10-06 23:22 UTC, dougaitken requested changes

2022-10-06 23:22 UTC, dougaitken commented on README.md
> +[Sticker Mule](/company-profiles/sticker-mule.md) | https://www.stickermule.com/ | Worldwide
Move this above Stitch Fix

2022-10-07 06:58 UTC, abhirimal commented on README.md
> +[Sticker Mule](/company-profiles/sticker-mule.md) | https://www.stickermule.com/ | Worldwide
sure

2022-10-07 18:26 UTC, abhirimal commented
@dougaitken i have updated the changes. please review.

2022-10-07 23:00 UTC, dougaitken approved these changes

2022-10-07 23:09 UTC, merged