Add new company - CODE LIKE A GIRL
remoteintech/remote-jobs pull request #1502
Opened 2022-10-10 00:36 UTC by sarahesbie

Added Code Like a Girl company profile and listing. Code Like a Girl are a remote tech company based in Australia. 

- [] This PR contains housekeeping only (URL edits, copy changes etc) - **if this is checked, delete other lines that don't apply.**
- [x] You are an employee of the company mentioned and confirm all included details are correct.
- [x] You know your alphabet - company is listed in alphabetical order in the README.md file.
- [x] The company directly hires employees. ** No bootcamps / freelance sites / etc**
- [x] The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such.
- [x] A [company profile](/company-profiles/example.md) is included - This is __required__ for new additions.
- [x] An entry has been added or edited within the [readme.md file](../../main/README.md).
- [x] __Remote status__ has details regarding how the culture includes remote employees, how the company integrated remote workers, etc
- [x] __Region__ details the geographic regions in which this company employees can reside. For more details see the instructions in the [example company profile](/company-profiles/example.md#region).
- [x] __How to apply__ details the best approach for new applications, page on site where open position are listed, and any other help available for job hunters

This is a modified version of the [Contributing Guidelines](../../main/.github/CONTRIBUTING.md).

If accepted, can you please add #hacktoberfest-accepted tag to the PR? <3

2022-10-11 23:54 UTC, dougaitken requested changes

2022-10-11 23:54 UTC, dougaitken commented on README.md
> +[Code Like a Girl](/company-profiles/code-like-a-girl.md) | https://codelikeagirl.com | Australia
Can you move this up a line, please? `code` comes before `codea`

2022-10-11 23:55 UTC, dougaitken commented
Hey @sarahesbie one small edit. This whole repo has the hacktoberfest topic so you'll get a contribution bump when this is merged. Thanks!

2022-10-12 11:29 UTC, sarahesbie commented
> Hey @sarahesbie one small edit. This whole repo has the hacktoberfest topic so you'll get a contribution bump when this is merged. Thanks!

Hey @dougaitken done! :)

2022-10-13 21:39 UTC, dougaitken approved these changes

2022-10-21 20:08 UTC, merged