fix: An Ungodly Ammount of Typos
remoteintech/remote-jobs pull request #1505
Opened 2022-10-10 09:41 UTC by KieranRobson

This Pull Request should adhere to the repository's [Code of Conduct](../../main/.github/CONTRIBUTING.md).

Title your pull request descriptively. `[edit X company]` or `[add new company - COMPANY]` 

Please read and check the boxes in the list below that apply!

If updating or adding a company, please include details here: _delete this and add details_

Check off this list as appropriate (add an `x` between the `[]`). It will be used by @dougaitken when reviewing your contribution.

- [x] This PR contains housekeeping only (URL edits, copy changes etc) - **if this is checked, delete other lines that don't apply.**

This is a modified version of the [Contributing Guidelines](../../main/.github/CONTRIBUTING.md).

---

Fixing some typos here, alot are the same fixes but no rush to merge as there are alot here!

2022-10-10 11:30 UTC, dougaitken commented
```
Ammount
```

I see what you did there 😏

2022-10-10 11:36 UTC, KieranRobson commented
> ```
> Ammount
> ```
> 
> I see what you did there 😏

That was totally deliberate... yes 👀

2022-10-10 11:58 UTC, dougaitken commented
This will take some time. I've found out. There is a difference between cowork and co-work so some instances might make sense. 

Also e-commerce vs ecommerce is a tricky one as well. 

Maybe I should get a glossary on this.

2022-10-10 12:48 UTC, KieranRobson commented
Good plan, I'll look into and could help, maybe pop it in the pr template like

- Any technical terms such as cowork or ecommerce match the [glossary definition] (page link)

2022-10-10 12:56 UTC, KieranRobson commented
I use a spell checker and it didn't like coworking so I updated as I went through

I've now read up on the differences so will go back through and update!

2022-10-12 13:49 UTC, dougaitken commented
Right, I was reading up a bit on this, one seems to be aimed at where you literally work in a place with others, and the other is when you work with your colleagues. 

It will take a bit to go through all the instances of this so I'm not sure how to draw this one.

2022-10-12 14:24 UTC, KieranRobson commented
We could close it and ignore all instances of cowork and hope theyre correct 😆 😉

2022-10-13 21:43 UTC, dougaitken commented
There's still a bunch in here I want though haha!

2022-10-21 21:54 UTC, KieranRobson commented
Will get this sorted tomorrow so we can get it merged! Been a bit busy with other projects and PhD to sit down and work through it

2022-10-22 18:36 UTC, KieranRobson commented
@dougaitken All co(-)working changes have been reverted other than the typod one!

2022-10-22 18:46 UTC, dougaitken requested changes

2022-10-22 18:46 UTC, dougaitken commented on company-profiles/intellum.md
> +You can see a listing of opportunities here https://apply.workable.com/intellum-inc/ and on Intellum's LinkedIn profile.oppu
the `oppu` at the end, typo?

2022-10-22 18:46 UTC, dougaitken commented
A single typo left @KieranRobson

2022-10-22 18:49 UTC, KieranRobson commented
*now* no more typos, although I haven't went through the newly merged ones, may have missed a typo or two

2022-10-30 22:10 UTC, dougaitken approved these changes

2022-10-30 22:11 UTC, merged