Add new company - Fiverr
remoteintech/remote-jobs pull request #1541
Opened 2022-10-15 21:31 UTC by FelipeFama

This Pull Request should adhere to the repository's [Code of Conduct](../../main/.github/CONTRIBUTING.md).

Title your pull request descriptively. `[edit X company]` or `[add new company - COMPANY]` 

Please read and check the boxes in the list below that apply!

If updating or adding a company, please include details here: _delete this and add details_

Check off this list as appropriate (add an `x` between the `[]`). It will be used by @dougaitken when reviewing your contribution.

- [] This PR contains housekeeping only (URL edits, copy changes etc) - **if this is checked, delete other lines that don't apply.**
- [] You are an employee of the company mentioned and confirm all included details are correct.
- [] You know your alphabet - company is listed in alphabetical order in the README.md file.
- [] The company directly hires employees. ** No bootcamps / freelance sites / etc**
- [] The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such.
- [] A [company profile](/company-profiles/example.md) is included - This is __required__ for new additions.
- [] An entry has been added or edited within the [readme.md file](../../main/README.md).
- [] __Remote status__ has details regarding how the culture includes remote employees, how the company integrated remote workers, etc
- [] __Region__ details the geographic regions in which this company employees can reside. For more details see the instructions in the [example company profile](/company-profiles/example.md#region).
- [] __How to apply__ details the best approach for new applications, page on site where open position are listed, and any other help available for job hunters

This is a modified version of the [Contributing Guidelines](../../main/.github/CONTRIBUTING.md).

2022-10-15 21:35 UTC, KieranRobson commented
See @Christian-Oleson comment on your other pull request as the same issues arise here: https://github.com/remoteintech/remote-jobs/pull/1539#pullrequestreview-1143229329

2022-10-15 21:35 UTC, KieranRobson commented on README.md
> +[Fiverr](/company-profiles/fiverr.md) | https://www.fiverr.com/ | North America, Asia
This should be above `Fivexl`

2022-10-16 00:58 UTC, FelipeFama commented on README.md
> +[Fiverr](/company-profiles/fiverr.md) | https://www.fiverr.com/ | North America, Asia
okay

2022-10-16 15:17 UTC, dougaitken requested changes
Please add region section back to the profile so it matches the regions mentioned in the readme

2022-10-16 20:22 UTC, KieranRobson commented on company-profiles/fiverr.md
> +## Office Locations
Quick change! 

`Office Locations` to `Office locations`

2022-10-21 20:26 UTC, dougaitken approved these changes

2022-10-21 20:29 UTC, merged

2022-10-21 20:29 UTC, dougaitken commented
Thanks @FelipeFama