add new company -  Brainstorm Force
remoteintech/remote-jobs pull request #1563
Opened 2022-10-22 19:47 UTC by nilanshsharma

This is a modified version of, and should adhere to, the [Contributing Guidelines](../../main/.github/CONTRIBUTING.md).

* [ ] This PR contains housekeeping only (URL edits, copy changes etc) - **if this is checked, delete other lines that don't apply**
* [ ] You are an employee of the company mentioned and confirm all included details are correct.
* [x] You know your alphabet - company is listed in alphabetical order in the README.md file.
* [x] The company directly hires employees. ** No bootcamps / freelance sites / etc**
* [x] The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such.
* [x] A [company profile](/company-profiles/example.md) is included - This is __required__ for new additions.
* [x] An entry has been added or edited within the [readme.md file](../../main/README.md).
* [x] __Remote status__ has details regarding how the culture includes remote employees, how the company integrated remote workers, etc
* [x] __Region__ details the geographic regions in which this company employees can reside. For more details see the instructions in the [example company profile](/company-profiles/example.md#region).
* [x] __How to apply__ details the best approach for new applications, page on site where open position are listed, and any other help available for job hunters

2022-10-23 08:35 UTC, KieranRobson approved these changes
Looks good to me!

2022-10-23 10:57 UTC, dougaitken requested changes

2022-10-23 10:57 UTC, dougaitken commented on company-profiles/brainstorm-force.md
> +Wordpress, QA Engineer, Seo, Angular, React, Copywriter, Ui Designer
WordPress - capital P.

2022-10-23 12:43 UTC, nilanshsharma commented
Hey @dougaitken I've made the change as you asked for.

2022-10-24 18:27 UTC, dougaitken commented
Thanks @nilanshsharma 

One final one I noticed, the region is India but another sentence hints are more globally distributed employees. Can you confirm and clarify that for me, please?

2022-10-25 08:12 UTC, nilanshsharma commented
Hey @dougaitken, I confirmed with the company and updated the status.

2022-10-25 08:29 UTC, dougaitken approved these changes

2022-10-25 08:29 UTC, dougaitken commented on company-profiles/brainstorm-force.md
> +India
Change this to Worldwide if that's correct please @nilanshsharma

2022-10-25 16:36 UTC, nilanshsharma commented
Hey @dougaitken all changes confirmed and updated as you asked for.

2022-10-29 22:25 UTC, dougaitken approved these changes

2022-10-30 22:12 UTC, merged

2022-10-30 22:12 UTC, dougaitken commented
Hey there, thanks for contributing, it is appreciated