Add: Company Profile - Positiwise
remoteintech/remote-jobs pull request #1650
Opened 2023-09-20 06:26 UTC by milesbrowntech

This is a modified version of, and should adhere to, the [Contributing Guidelines](../../main/.github/CONTRIBUTING.md).

* [ ] This PR contains housekeeping only (URL edits, copy changes etc) - **if this is checked, delete other lines that don't apply**
* [x] You are an employee of the company mentioned and confirm all included details are correct.
* [x] You know your alphabet - company is listed in alphabetical order in the README.md file.
* [x] The company directly hires employees. ** No bootcamps / freelance sites / etc**
* [x] The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such.
* [x] A [company profile](/company-profiles/example.md) is included - This is __required__ for new additions.
* [x] An entry has been added or edited within the [readme.md file](../../main/README.md).
* [x] __Remote status__ has details regarding how the culture includes remote employees, how the company integrated remote workers, etc
* [x] __Region__ details the geographic regions in which this company employees can reside. For more details see the instructions in the [example company profile](/company-profiles/example.md#region).
* [x] __How to apply__ details the best approach for new applications, page on site where open position are listed, and any other help available for job hunters

2023-09-20 11:36 UTC, KieranRobson requested changes
Couple changes to be made.

2023-09-20 11:36 UTC, KieranRobson commented on company-profiles/positiwise.md
> +# Company blurb
```suggestion
# Positiwise 

## Company blurb

```

2023-09-20 11:36 UTC, KieranRobson commented on company-profiles/positiwise.md
> +https://positiwise.com
```suggestion
Find job openings here: https://positiwise.com/careers
```

2023-09-21 04:09 UTC, milesbrowntech commented on company-profiles/positiwise.md
> +# Company blurb
@KieranRobson this has been resolved.

2023-09-21 04:09 UTC, milesbrowntech commented on company-profiles/positiwise.md
> +https://positiwise.com
@KieranRobson this has been resolved.

2023-09-21 09:21 UTC, KieranRobson requested changes
Company Blurb needs to be added

2023-09-21 09:21 UTC, KieranRobson commented on company-profiles/positiwise.md
> +Positiwise.com now offers a wide range of services, including Custom Software Development, with expertise in both Python and .NET technologies. Our skilled team is proficient in crafting tailored sol
```suggestion
# Positiwise

## Company Blurb
Positiwise.com now offers a wide range of services, including Custom Software Development, with expertise in both Python and .NET technologies. Our skilled team is proficient in crafting tailored solutions to meet your unique business needs. Trust us for top-notch .NET development services, backed by a proven track record of excellence in the industry.

```

2023-09-22 05:45 UTC, milesbrowntech commented
@KieranRobson Company Blurb has been added!

2023-09-22 09:52 UTC, KieranRobson commented on company-profiles/positiwise.md
> +## Company Blurb
Woops, this is meant to be a lowercase B, My mistake

```suggestion
## Company blurb
```

2023-09-22 09:54 UTC, KieranRobson approved these changes
Looks good to me!

2023-09-30 15:58 UTC, merged