add new company - Accor
remoteintech/remote-jobs pull request #1657
Opened 2023-10-01 10:24 UTC by dhruvchandak30

This is a modified version of, and should adhere to, the [Contributing Guidelines](../../main/.github/CONTRIBUTING.md).

* [ ] This PR contains housekeeping only (URL edits, copy changes etc) - **if this is checked, delete other lines that don't apply**
* [ ] You are an employee of the company mentioned and confirm all included details are correct.
* [x] You know your alphabet - company is listed in alphabetical order in the README.md file.
* [x] The company directly hires employees. ** No bootcamps / freelance sites / etc**
* [x] The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such.
* [x] A [company profile](/company-profiles/example.md) is included - This is __required__ for new additions.
* [x] An entry has been added or edited within the [readme.md file](../../main/README.md).
* [x] __Remote status__ has details regarding how the culture includes remote employees, how the company integrated remote workers, etc
* [x] __Region__ details the geographic regions in which this company employees can reside. For more details see the instructions in the [example company profile](/company-profiles/example.md#region).
* [x] __How to apply__ details the best approach for new applications, page on site where open position are listed, and any other help available for job hunters

2023-10-01 11:34 UTC, dhruvchandak30 commented
@KieranRobson  Can you please add `hacktoberfest` and `hacktoberfest-accepted` labels.
It would be a great help for me.

2023-10-01 17:46 UTC, dougaitken requested changes

2023-10-01 17:46 UTC, dougaitken commented on company-profiles/accor.md
> +France, Issy-les-Moulineaux
Region is where the company hires - the section above lists 110 countries so I'd recommend using worldwide if they hire remotely in those countries

2023-10-01 17:46 UTC, dougaitken commented
@dhruvchandak30 The repository is labelled hacktoberfest so you'll get the participation.

Can you check my review please?

2023-10-01 17:52 UTC, dhruvchandak30 commented
> @dhruvchandak30 The repository is labelled hacktoberfest so you'll get the participation.
> 
> Can you check my review please?

Yes, Done with the changes

2023-10-01 18:30 UTC, dougaitken approved these changes

2023-10-02 08:29 UTC, dhruvchandak30 commented
@dougaitken Can you please merge this PR, as I have pushed from my main branch, I am not able to make more PR (I am but it is also showing these two commits).

2023-10-08 21:47 UTC, dougaitken commented
> as I have pushed from my main branch, I am not able to make more PR (I am but it is also showing these two commits).

best to use branches for new features rather than `main` 😉

2023-10-08 21:47 UTC, merged