Added a new Company Named Basis Point Design
remoteintech/remote-jobs pull request #1662
Opened 2023-10-01 20:29 UTC by AnuragNishad12

Just Add a new Company In .md files called "Basis Point Design Ltd" 

Company Website :-
https://basispoint.design/

<img width="948" alt="image" src="https://github.com/remoteintech/remote-jobs/assets/124987038/28d324b3-3b41-471c-bd63-e50ff3844a2e">

2023-10-02 11:47 UTC, KieranRobson requested changes
Couple of changes to be made.

2023-10-02 11:47 UTC, KieranRobson commented on README.md
>  [Basecamp](/company-profiles/basecamp.md) | https://basecamp.com/ | Worldwide
Incorrect Order.

```suggestion
[Bandcamp](/company-profiles/bandcamp.md) | https://bandcamp.com/ | Worldwide
[BandLab](/company-profiles/bandlab.md) | https://bandlab.com/ | Worldwide
[Bandzoogle](/company-profiles/bandzoogle.md) | https://bandzoogle.com/ | Worldwide
[Baremetrics](/company-profiles/baremetrics.md) | https://baremetrics.com/ | Worldwide
[Basecamp](/company-profiles/basecamp.md) | https://basecamp.com/ | Worldwide
[BasisPointDesign](/company-profiles/basisPointDesignLtd.md) | https://basispoint.design/ | Portugal, South Africa
```

2023-10-02 11:47 UTC, KieranRobson commented on company-profiles/basisPointDesignLtd.md
> +# basisPointDesignLtd
Filename must match the Title.

```suggestion
# basisPointDesignltd
```

2023-10-02 11:49 UTC, KieranRobson commented on company-profiles/basisPointDesignLtd.md
> +# basisPointDesignltd
```suggestion
# basispointdesignltd
```

2023-10-08 21:54 UTC, dougaitken commented on company-profiles/basisPointDesignLtd.md
> +# basispointdesignltd
The company name and file name should match the name listed in the readme.md file. This company is listed as `BasisPointDesign` so the file name should be `basispointdesign.md` and the title here should be `# BasisPointDesign`

2023-10-08 21:55 UTC, dougaitken commented on company-profiles/basisPointDesignLtd.md
> +Branding, Graphic Design, Marketing Presentations, Website Design, Website Development, Marketing Communications, Investor Communications, Pitch Deck Design, Digital Design, Investor Portal Design an
This copy has nothing to do with the remote status. As mentioned [in the example](https://github.com/remoteintech/remote-jobs/blob/main/company-profiles/example.md#remote-status), this should related to the remote culture of the company.

2023-10-08 21:56 UTC, dougaitken commented on company-profiles/basisPointDesignLtd.md
> +England
The region is where remote employees are accepted - https://github.com/remoteintech/remote-jobs/blob/main/company-profiles/example.md#region - this doesn't match the region in the readme file.

2023-10-08 21:59 UTC, dougaitken commented on company-profiles/basisPointDesignLtd.md
> +Visit https://basispoint.design/
I don't see any mention about open careers or remote employment. Can you add context, please?

2023-10-08 21:59 UTC, dougaitken requested changes
Please review the comments and fix before this will be merged, otherwise it will be closed without merging as invalid

2023-11-14 00:05 UTC, closed without merging