added company - Atento
remoteintech/remote-jobs pull request #1664
Opened 2023-10-02 16:50 UTC by shailendrakawadkar

This is a modified version of, and should adhere to, the [Contributing Guidelines](../../main/.github/CONTRIBUTING.md).

* [ ] This PR contains housekeeping only (URL edits, copy changes etc) - **if this is checked, delete other lines that don't apply**
* [ ] You are an employee of the company mentioned and confirm all included details are correct.
* [ ] You know your alphabet - company is listed in alphabetical order in the README.md file.
* [ ] The company directly hires employees. ** No bootcamps / freelance sites / etc**
* [ ] The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such.
* [ ] A [company profile](/company-profiles/example.md) is included - This is __required__ for new additions.
* [ ] An entry has been added or edited within the [readme.md file](../../main/README.md).
* [ ] __Remote status__ has details regarding how the culture includes remote employees, how the company integrated remote workers, etc
* [ ] __Region__ details the geographic regions in which this company employees can reside. For more details see the instructions in the [example company profile](/company-profiles/example.md#region).
* [ ] __How to apply__ details the best approach for new applications, page on site where open position are listed, and any other help available for job hunters

2023-10-02 16:59 UTC, shailendrakawadkar commented
@KieranRobson added new company from list, please verify

2023-10-02 17:03 UTC, KieranRobson requested changes
Clean up of white space

2023-10-02 17:03 UTC, KieranRobson commented on company-profiles/atento.md
> +[Click Here to apply](https://atento.gupy.io/)
```suggestion
##  How to apply
[Click Here to apply](https://atento.gupy.io/)
```

2023-10-02 17:03 UTC, KieranRobson commented on company-profiles/atento.md
> + - Buenos Aires, Buenos Aires Province, Argentina
```suggestion
 - Miramar, FL, United States
 - San Antonio, TX, United States
 - Pleasant Grove, UT, United States
 - Buenos Aires, Buenos Aires Province, Argentina
```

2023-10-02 17:03 UTC, KieranRobson commented on company-profiles/atento.md
> +Our unique expertise lies in combining data technology and digital tools with decades of experience in customer experience. This allows us to provide valuable insights for every step of the end/custo
```suggestion
##  Company technologies
Our unique expertise lies in combining data technology and digital tools with decades of experience in customer experience. This allows us to provide valuable insights for every step of the end/customer's journey, resulting in more valuable experiences for consumers and companies.
```

2023-10-02 17:03 UTC, KieranRobson commented on company-profiles/atento.md
> +Brazil, Mexico and EMEA
```suggestion
##  Region
Brazil, Mexico and EMEA
```

2023-10-02 17:03 UTC, KieranRobson commented on company-profiles/atento.md
> +You will be working from home on an Atento PC, so there is an expectation that you are organized and self driven.
```suggestion
##  Remote status
You will be working from home on an Atento PC, so there is an expectation that you are organized and self driven.
```

2023-10-02 17:03 UTC, KieranRobson commented on company-profiles/atento.md
> +
```suggestion
##  Company size
92,663 employees on LinkedIn

```

2023-10-02 17:03 UTC, KieranRobson commented on company-profiles/atento.md
> +Over 200,000 people trust Atlassian.
```suggestion
##  Company blurb
Over 200,000 people trust Atlassian.
```

2023-10-02 17:03 UTC, KieranRobson commented on company-profiles/atento.md
> +##  Company blurb
```suggestion
#  Atento

##  Company blurb
```

2023-10-02 17:10 UTC, shailendrakawadkar commented on company-profiles/atento.md
> + - Buenos Aires, Buenos Aires Province, Argentina
removed

2023-10-02 17:10 UTC, shailendrakawadkar commented on company-profiles/atento.md
> +Our unique expertise lies in combining data technology and digital tools with decades of experience in customer experience. This allows us to provide valuable insights for every step of the end/custo
removed

2023-10-02 17:11 UTC, shailendrakawadkar commented on company-profiles/atento.md
> +Brazil, Mexico and EMEA
removed

2023-10-02 17:11 UTC, shailendrakawadkar commented
@KieranRobson  removed spaces

2023-10-02 17:12 UTC, KieranRobson commented
Logs arent loading and I cannot see why the tests are failing. 

Give me a bit of time before reviewing to see if they load.

2023-10-02 19:04 UTC, KieranRobson requested changes
Quick change to be made

2023-10-02 19:04 UTC, KieranRobson commented on README.md
> +[Atento](/company-profiles/atento.md) | https://atento.gupy.io | Brazil, Mexico and EMEA
```suggestion
[Atento](/company-profiles/atento.md) | https://atento.gupy.io | Brazil, Mexico and EMEA
[Atlassian](/company-profiles/atlassian.md) | https://www.atlassian.com/ | USA, Europe, Asia, Australia
```

2023-10-03 05:21 UTC, shailendrakawadkar commented on README.md
> +[Atento](/company-profiles/atento.md) | https://atento.gupy.io | Brazil, Mexico and EMEA
fixed ordering

2023-10-03 05:22 UTC, shailendrakawadkar commented
@KieranRobson fixed ordering, please check.

2023-10-08 22:16 UTC, merged