Add new company: Renaissance
remoteintech/remote-jobs pull request #1691
Opened 2023-10-10 14:03 UTC by dhruvchandak30

This is a modified version of, and should adhere to, the [Contributing Guidelines](../../main/.github/CONTRIBUTING.md).

* [ ] This PR contains housekeeping only (URL edits, copy changes etc) - **if this is checked, delete other lines that don't apply**
* [ ] You are an employee of the company mentioned and confirm all included details are correct.
* [x] You know your alphabet - company is listed in alphabetical order in the README.md file.
* [x] The company directly hires employees. ** No bootcamps / freelance sites / etc**
* [x] The company hires remote employees, or positions are available to remote workers and are clearly illustrated as such.
* [x] A [company profile](/company-profiles/example.md) is included - This is __required__ for new additions.
* [x] An entry has been added or edited within the [readme.md file](../../main/README.md).
* [x] __Remote status__ has details regarding how the culture includes remote employees, how the company integrated remote workers, etc
* [x] __Region__ details the geographic regions in which this company employees can reside. For more details see the instructions in the [example company profile](/company-profiles/example.md#region).
* [x] __How to apply__ details the best approach for new applications, page on site where open position are listed, and any other help available for job hunters

fixes: #1206

2023-10-10 14:10 UTC, KieranRobson requested changes
Changes to be made.

2023-10-10 14:10 UTC, KieranRobson commented on company-profiles/renaissance.md
> +[Click Here to apply](https://careers.smartrecruiters.com/Renaissance)
The layout and headings are standardised, see your other PR for correct layout #1687

2023-10-10 14:17 UTC, KieranRobson commented
Thanks for the speedy changes, let me know when it is ready for review!

2023-10-10 14:18 UTC, dhruvchandak30 commented
> Thanks for the speedy changes, let me know when it is ready for review!

@KieranRobson  It is ready for review.

2023-10-10 14:25 UTC, dhruvchandak30 commented on company-profiles/renaissance.md
> +## Company technologies
It is nowhere mention which Technologies they use. Should I remove this section?

2023-10-11 13:06 UTC, dougaitken commented on company-profiles/renaissance.md
> +## Company technologies
Not ideal but keep the header for the section and leave it blank. The company is aimed at technology but it's not even clear on their job listings what technologies they use.

2023-10-11 13:10 UTC, dougaitken requested changes
change the region in the readme line removing UK, and delete the content but keep the header for `Company technologies` @dhruvchandak30

2023-10-11 13:10 UTC, dougaitken commented on README.md
> +[Renaissance](/company-profiles/renaissance.md) | https://www.renaissance.com/ | United States, UK
I don't see anything on the site about UK so let's remove that and keep it as `United States`

2023-10-17 13:45 UTC, dougaitken approved these changes

2023-10-17 13:48 UTC, dougaitken commented
@dhruvchandak30 Sorry for the delay. If you can, can you remove the Company technologies header? The build is complaining and I forgot a header needs to be removed if it's empty.

2023-10-18 03:27 UTC, dhruvchandak30 commented
> @dhruvchandak30 Sorry for the delay. If you can, can you remove the Company technologies header? The build is complaining and I forgot a header needs to be removed if it's empty.

Sure, I will remove it.

2023-10-22 11:34 UTC, dhruvchandak30 commented
@dougaitken  I have removed the Technologies' Header.

2023-10-25 10:12 UTC, dougaitken approved these changes

2023-10-25 10:12 UTC, merged