Main
remoteintech/remote-jobs pull request #1744
Opened 2023-10-22 03:01 UTC by aadeshmodak13

added new companis #1685

2023-10-23 12:46 UTC, KieranRobson commented
Please add it to the README aswell.

2023-10-25 10:24 UTC, dougaitken commented
@aadeshmodak13  When you create a Pull Request in this this repository there is a Pull Request template with a checklist - you've deleted this when submitting this PR.

If you had left that checklist and reviewed each option you would have seen that there is mention of what @KieranRobson has asked for. 

https://github.com/remoteintech/remote-jobs/blob/7f10ae795f64c19b24c2bebba7c51629a0103b86/.github/PULL_REQUEST_TEMPLATE.MD?plain=1#L29

I've added some comments to the profile for you to fix. Thanks.

2023-10-25 10:26 UTC, dougaitken requested changes

2023-10-25 10:26 UTC, dougaitken commented on company-profiles/tempesta.md
> +## Comapny size
Spelling - `Company size`

2023-10-25 10:26 UTC, dougaitken commented on company-profiles/tempesta.md
> +## remote status
Capitalise the first letter. `Remote status`

2023-10-25 10:26 UTC, dougaitken commented on company-profiles/tempesta.md
> +## region
Capitalise - `Region`

2023-10-25 10:26 UTC, dougaitken commented on company-profiles/tempesta.md
> +## company technologies
Capitalise the first letter. `Remote status`

2023-10-25 10:26 UTC, dougaitken commented on company-profiles/tempesta.md
> +## office locations
Capitalise the first letter. `Office locations`

2023-10-25 10:26 UTC, dougaitken commented on company-profiles/tempesta.md
> +## how to apply
Capitalise the first letter. `How to apply`

2023-11-14 00:26 UTC, closed without merging

2023-11-14 00:26 UTC, dougaitken commented
Closing, no author reply.